from __future__ import annotations

import argparse
import json
import os
import tempfile
import time
from pathlib import Path

import numpy as np

from .common import load_shards
from .config import ROOT, load_config

RUNTIME = '''

def score(x):
    """Raw (pre-sigmoid) model score for one feature vector."""
    total = 0.0
    split_offset = 0
    leaf_offset = 0
    for depth in _DEPTHS:
        leaf = 0
        bit = 1
        for index in range(split_offset, split_offset + depth):
            if x[_SF[index]] > _SB[index]:
                leaf += bit
            bit += bit
        total += _LV[leaf_offset + leaf]
        split_offset += depth
        leaf_offset += 1 << depth
    return total * _SCALE + _BIAS
'''


def load_json_model(model_path: Path):
    from catboost import CatBoostClassifier

    model = CatBoostClassifier()
    model.load_model(model_path)
    with tempfile.NamedTemporaryFile("r", suffix=".json", delete=False) as file:
        temporary_path = file.name
    try:
        model.save_model(temporary_path, format="json")
        with open(temporary_path, encoding="utf-8") as file:
            model_json = json.load(file)
    finally:
        os.unlink(temporary_path)
    return model, model_json


def main() -> None:
    parser = argparse.ArgumentParser(description="Export CatBoost trees as pure Python.")
    parser.add_argument("--config", required=True)
    parser.add_argument("--run", required=True)
    parser.add_argument("--out", help="output path; defaults to <run>/model_data.py")
    parser.add_argument("--publish", action="store_true",
                        help="write the configured production model and manifest")
    parser.add_argument("--verify-rows", type=int, default=2000)
    args = parser.parse_args()
    if args.publish and args.out:
        raise SystemExit("use either --publish or --out, not both")

    config = load_config(args.config)
    run_dir = Path(args.run)
    manifest = json.loads((run_dir / "run_manifest.json").read_text(encoding="utf-8"))
    data_dir = ROOT / manifest["dataset"]
    with open(data_dir / "features.json", encoding="utf-8") as file:
        feature_metadata = json.load(file)
    if manifest["feature_version"] != feature_metadata["version"]:
        raise SystemExit("feature version mismatch between run and dataset")
    if manifest["feature_count"] != len(feature_metadata["names"]):
        raise SystemExit("feature count mismatch between run and dataset")

    production_output = ROOT / config["production_model"] if args.publish else None
    output = run_dir / ".model_data.publish.tmp.py" if args.publish else Path(
        args.out or run_dir / "model_data.py"
    )
    model, model_json = load_json_model(run_dir / "model.cbm")
    trees = model_json["oblivious_trees"]
    scale, bias = model_json.get("scale_and_bias", [1.0, [0.0]])
    bias = bias[0] if isinstance(bias, list) else bias
    depths: list[int] = []
    split_features: list[int] = []
    split_borders: list[float] = []
    leaf_values: list[float] = []
    for tree in trees:
        splits = tree["splits"]
        if any(split.get("split_type") != "FloatFeature" for split in splits):
            raise SystemExit("only float feature splits are supported")
        split_features.extend(int(split["float_feature_index"]) for split in splits)
        split_borders.extend(float(split["border"]) for split in splits)
        depths.append(len(splits))
        leaf_values.extend(float(value) for value in tree["leaf_values"])
    used = model_json["features_info"]["float_features"]
    remap = {int(item["feature_index"]): int(item["flat_feature_index"]) for item in used}
    split_features = [remap[index] for index in split_features]

    output.parent.mkdir(parents=True, exist_ok=True)
    with output.open("w", encoding="utf-8") as file:
        file.write('"""Generated by scripts.catboost.export - do not edit."""\n')
        file.write(f"# run: {manifest['run_id']}  trees={len(depths)}\n\n")
        file.write(f"N_TREES = {len(depths)}\n_SCALE = {scale!r}\n_BIAS = {bias!r}\n")
        file.write(f"_DEPTHS = {depths!r}\n_SF = {split_features!r}\n")
        file.write("_SB = [" + ",".join(f"{value:.9g}" for value in split_borders) + "]\n")
        file.write("_LV = [" + ",".join(f"{value:.9g}" for value in leaf_values) + "]\n")
        file.write(RUNTIME)

    sample = load_shards(str(data_dir), max_episodes=20)["X"][:args.verify_rows]
    namespace: dict = {}
    exec(compile(output.read_text(encoding="utf-8"), str(output), "exec"), namespace)
    python_scores = np.array([namespace["score"](row.tolist()) for row in sample])
    reference = model.predict(sample, prediction_type="RawFormulaVal")
    error = float(np.abs(python_scores - reference).max())
    started = time.perf_counter()
    repetitions = min(500, len(sample))
    for row in sample[:repetitions].tolist():
        namespace["score"](row)
    milliseconds = (time.perf_counter() - started) / repetitions * 1000
    print(f"wrote {output}: trees={len(depths)} max_error={error:.3e} "
          f"speed={milliseconds:.3f}ms/option")
    if error > 1e-5:
        raise SystemExit("pure-Python output differs from CatBoost")
    if args.publish:
        production_output.parent.mkdir(parents=True, exist_ok=True)
        os.replace(output, production_output)
        print(f"published -> {production_output}")
        production_manifest = ROOT / config["production_manifest"]
        production_manifest.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
        print(f"manifest -> {production_manifest}")


if __name__ == "__main__":
    main()